### ISSUE TITLE
Error with Microsoft Edge browser

### ISSUE THREAD

**Issue by simplecommerce** [vazco/meteor-universe-i18n#98] opened 2018-08-01 23:55 UTC
Hi,

I think there is a bug with your package on Microsoft Edge browser.
In chrome, my app loads fine.
But in Edge, it crashes.

I tried the following.

meteor create test-project
meteor npm install
meteor add universe:i18n
meteor

And in the browser, this is what I get.

SCRIPT1028: SCRIPT1028: Expected identifier, string or number universe_i18n.js (1884,11)
SCRIPT5007: Unable to get property '_i18n' of undefined or null reference global-imports.js (6,1)
SCRIPT5009: 'meteorInstall' is not defined app.js (1,1)

When I remove the package using Meteor remove universe:i18n, it loads fine.

Any idea on how to fix this or when it will be fixed?

Thanks!

**Comment by idmadj** [comment] 2018-08-10 04:57
This is caused by the `async` variable in client/api.js ([here](https://github.com/vazco/meteor-universe-i18n/blob/81bd6e6a2f299fa5bdf8eb25c2be5cc38be370a9/client/api.js#L6)). Edge chokes on it because `async` is a reserved keyword in ES2017.

I've submitted a fix (PR #102)

**Comment by simplecommerce** [comment] 2018-08-10 10:52
@idmadj Thanks, I thought that could be the issue but i didn't know how to fix it and test it directly.

Awesome!

**Comment by idmadj** [comment] 2018-08-10 19:53
Happy to help! Can you keep the issue open until the PR is merged or a different solution makes it to master?

**Comment by simplecommerce** [comment] 2018-08-10 21:13
No problem!!

**Closed** 2018-11-13 18:31 UTC
