### ISSUE TITLE
getLanguages() not returning what is expected

### ISSUE THREAD

**Issue by yanickrochon** [vazco/meteor-universe-i18n#35] opened 2016-09-09 19:07 UTC
I have currently two supported locales in my app; "en" and "fr". And I want to display a selection of available locales so that the user may switch from the front-end.

By default, "en" is selected when the app start and / or if the user hasn't setup a preferred locale. So, the problem is this :

``` js
i18n.getLanguages();
// -> ["en"]

i18n.setLocale('fr');
// -> [Promise]

i18n.getLanguages();
// -> ["en", "fr"]

i18n.setLocale('es');     // no such translation file exists
// -> [Promise]

i18n.getLanguages();
// -> ["en", "fr", "es"]            ???
```

Is it possible to return _all_ the locales that actually exists and has at least one translation available, at any time? Is it possible not to show locales that has no translations?

**Comment by radekmie** [comment] 2016-09-24 14:22
Hey @yanickrochon - sorry for this long delay.

**Investigation story:**

This is caused by [`getJS` implementation](https://github.com/vazco/meteor-universe-i18n/blob/master/server/api.js#L54-L66). If you call `i18n.setLocale`, [it will try to load your translations](https://github.com/vazco/meteor-universe-i18n/blob/master/lib/i18n.js#L33-L50) which without translations look like this:

```js
(Package['universe:i18n'].i18n).addTranslations('xx', {});
```

[It results in `i18n._translations['xx'] = {}`](https://github.com/vazco/meteor-universe-i18n/blob/master/lib/i18n.js#L209-L226). Now look at [`i18n.getLanguages` implementation](https://github.com/vazco/meteor-universe-i18n/blob/master/lib/i18n.js#L248-L261).

**Solution:**

Well, three solutions:

0. _(if possible)_ Call `setLocale` with `{noDownload: true}`.
0. Change `getJS` to simply pass a noop script if no translations exists.
0. Change `getLanguages` to return only _non-empty_ languages.

**Comment by yanickrochon** [comment] 2016-11-10 17:16
Well, exactly. The problem is that it extends the `i18n._translations` object regardless if translations exist or not, thus create new locales even on unsupported ones. There is a reason why `setLocale` returns a promise, and this snippet should be the proper behavior

```js

i18n.setLocale('es').then(() => {
  i18n.getLanguages();
  // -> ['en', 'es']     if 'es' exists at all
  // -> ['en']           if not
});
i18n.getLanguages();
// -> ['en']
```

Where the result when executing this code should be evident. I fail to see how this could break anything? Is there anyone expecting this behavior

```js
i18n.setLocale('zu');
console.log( i18n.getLanguages() );
// -> ['en', 'zu']
```

when the actual available locales do not support `zu` ?

In fact, the server should sync the available locales to the client, in the sense that

```js
i18n.getLanguages();
// -> ['en', 'es', 'fr']

i18n.isLoaded('en');      // true
i18n.isLoaded('es');      // false
i18n.isLoaded('fr');      // false
```

Which would be consistent with `i18n.setLocale()` and `i18n.loadLocale()`.

**Comment by janowsiany** [comment] 2017-03-03 17:49
Solved by #60, closing.

**Closed** 2017-03-03 17:49 UTC
Labels: bug

**Comment by yanickrochon** [comment] 2017-03-03 18:07
Thanks! Will test this out as soon as I can.

**Comment by janowsiany** [comment] 2017-03-03 18:12
Great, let us know if it worked.
