### ISSUE TITLE
he locale not working

### ISSUE THREAD

**Issue by sirpy** [vazco/meteor-universe-i18n#95] opened 2018-06-21 11:46 UTC
I have two files he-IL.i18n.json and he.i18n.json the first one work but the other doesnt.
setLocale('he-IL') works setLocale('he') doesn't

**Comment by MacRusher** [comment] 2019-03-14 12:15
Both `he` and `he-IL` are on the list of supported languages. Does this issue still occur for you? If so, can you provide minimal reproduction steps or repository where other languages are working, and `he` is not?

**Comment by piotrpospiech** [comment] 2021-09-24 13:15
Both locales work in the newest version of package. I can't reproduce problem. I close the issue.

**Closed by piotrpospiech** 2021-09-24 13:15 UTC
Labels: bug, to check
