### ISSUE TITLE
Loading Translation Files

### ISSUE THREAD

**Issue by vjhameed** [vazco/meteor-universe-i18n#112] opened 2019-02-21 16:16 UTC
Hi 

I have everything according to the meteor tutorials. But it just dosen't seem to load the translation files. They are in a directory named both in the root of the project.

**Comment by mozfet** [comment] 2019-04-14 12:29
In one of my projects it works. In another not...

**Comment by mozfet** [comment] 2019-04-14 14:08
I've updated both projects to the latest of everything and compared their versions files. It still only works in the one, and not the other. All Meteor dependancies are the same, the package that works has a few additional packages though, but they do not seem related to this package.

I'm using:
* Meteor 1.8.1
* universe:i18n@1.20.1
* universe:i18n-blaze@1.5.1

In both projects, the translation file is stored in ```./both/locale/en-us.i18n.yml``` of the application project folder. 

I can see Meteor build detects the yml file when I change and save it, the server resets, however, the client is not reloaded. It does not start working if I refresh the browser either.

In the browser JS console on localhost:3000 after page has loaded:
```i18n.getLanguages('name')``` returns ```[]```

In ```imports/startup/client/locale.js```, which is imported by ```imports/startup/client/index.js``` : ```i18n.setLocale('en-US')``` works, but i18n.getLanguages('name') is also empty.

The yml file that that works is substantially larger and more complex, the yml file that does not work contains only:
```
  _locale: 'en-US'
_splitKey: '.'
_namespace: "GYR"

title: Fullstack
home.header: Home
```

I'm using Blaze and since there is no translations loaded, this also does not work:
```html
{{__ "GYR.title"}}
{{__ "GYR.home.header"}}
```

Spent more than 4 hours trying to solve this... I'm at a loss.

**Comment by mozfet** [comment] 2019-04-14 14:09
To make things worse, the project that does work is an earlier branch of the project that does not work!

**Comment by mozfet** [comment] 2019-04-14 14:41
I figured the only thing I haven't done was check that the npm ```package.json``` of both projects for being the same... it turns out that this breaks it for the working project, and is inside the broken project:
```
{
  ...
 "meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    },
    "testModule": "tests/main.js"
  }
}
```

It seems that by having this configuration, eager loading is being disabled. Which probably is the reason why the translation file is not detected.

**Comment by mgscreativa** [comment] 2019-04-22 18:48
Hi @mozfet! I can confirm that removing this from package.json makes this module to work again!

> {
>   ...
>  "meteor": {
>     "mainModule": {
>       "client": "client/main.js",
>       "server": "server/main.js"
>     },
>     "testModule": "tests/main.js"
>   }
> }

**Comment by mozfet** [comment] 2019-04-22 18:57
I think that a file loading function in the API would help remove this problem.

**Comment by niklasdahlheimer** [comment] 2021-01-13 19:34
This is still in issue in 2021. I read the tutorials up and down to find out what I've done wrong and finally this post was the solution for me. Are there any plans to fix this?

**Comment by piotrpospiech** [comment] 2021-10-13 11:42
Issue couldn't be reproduced with `meteor v2.4` and `meteor-universe-i18n v1.32.2`, so I will close this issue. If you still occur this problem, let me know and I will reopen discussion.

**Closed by piotrpospiech** 2021-10-13 11:42 UTC

**Comment by Clickrouc** [comment] 2022-04-27 10:31
Problem is occur with `meteor v2.7.1` and `meteor-universe-i18n v1.32.6`
