### ISSUE TITLE
Cannot find module 'meteor/universe:i18n'.

### ISSUE THREAD

**Issue by K69G4JRA725W** [vazco/meteor-universe-i18n#63] opened 2017-03-13 09:06 UTC
Hello, 

I am trying to use universe:i18n in my Angular2 meteor project. I followed the instructions:
      meteor add universe:i18n
      import i18n from 'meteor/universe:i18n';

But I keep getting  this message:  " Cannot find module 'meteor/universe:i18n'.  "    this the call   to  i18n.__(key)   is successful. 

My directory structure is like:   
/assets     en.i18n.json     fr.i18n.json
/client
/server

Even though there are fr and en json files, only en is picked up. I could not figure out why. Please help. Thanks a lot!

My email is: 858190729@qq.com

**Comment by janowsiany** [comment] 2017-03-14 12:56
Hello there, sorry for a delay. Could you please provide some minimal repository for reporduction?

**Comment by janowsiany** [comment] 2017-03-16 09:58
@K69G4JRA725W ?

**Comment by K69G4JRA725W** [comment] 2017-03-16 10:01
Can you provide a complete working example for Angular Meteor Universe:i18n , please?

**Comment by janowsiany** [comment] 2017-03-23 20:47
Closing this issue as i cant reproduce this. If @K69G4JRA725W want to share reproduction repository then please do this in this issue.

**Closed by janowsiany** 2017-03-23 20:47 UTC
