### ISSUE TITLE
Strange server fetch (expecting json but return javascript)

### ISSUE THREAD

**Issue by dokithonon** [vazco/meteor-universe-i18n#148] opened 2022-01-05 11:42 UTC
Hello,
We encounter an error with package version 1.32.4 and meteor 2.5.2.

On the server data.json() return an error after this fetch 
![Screenshot 2022-01-05 at 12 38 56](https://user-images.githubusercontent.com/1856638/148212020-6c0013ac-335f-49bf-bf66-753287ca500d.png)

This seems normal to have this error because the content of the file is not a JSON 

![Screenshot 2022-01-05 at 12 41 30](https://user-images.githubusercontent.com/1856638/148212184-6b9a305b-3a3a-4885-a91e-9e4f4a0cb711.png)

But We don't understand why the server is expecting a JSON at this url.
Thanks for your feedbacks on this.

**Comment by zendranm** [comment] 2022-01-10 12:53
Hi @dokithonon, thanks for your question. We suspect that this issue is related to the other one #147. We couldn't reproduce this behavior (neither the #147). Could you provide a basic reproduction code (possibly some repository) so we can further investigate this issue? Especially, can you specify how your translation files look like?

**Comment by zendranm** [comment] 2022-01-31 15:12
Hi @dokithonon, since there is no reproduction of this problem I am closing this issue for now. I'll reopen it once there's a reproduction for it.

**Closed by zendranm** 2022-01-31 15:12 UTC
Labels: question
